.PHONY: all clean

PKG = i686-w64-mingw32-pkg-config
CC = i686-w64-mingw32-gcc

TARGET = soulfu
SRC = source/soulfu.c
DEP = $(wildcard source/*.c source/*.h)
LDLIBS = $(shell $(PKG) --libs sdl SDL_net ogg libjpeg vorbis) -lopengl32
FLAGS = -DDEVTOOL

all: $(TARGET) data

clean:
	rm -rf $(TARGET) $(DATAFILE)

$(TARGET): $(DEP)
	$(CC) $(FLAGS) -o $@ -Isource $(SRC) $(LDLIBS)

include common.mk
