.PHONY: all

PKG = i686-w64-mingw32-pkg-config
CC = i686-w64-mingw32-gcc
WINDRES = i686-w64-mingw32-windres

TARGET = soulfu
SRC = source/soulfu.c
DEP = $(wildcard source/*.c source/*.h)
LDLIBS = -lSDL -lSDL_net -l:libjpeg.a -l:libvorbis.a -l:libogg.a -lopengl32
FLAGS = -DDEVTOOL

all: $(TARGET) data

$(TARGET): $(DEP) resource.res
	$(CC) $(FLAGS) -o $@ -Isource $(SRC) resource.res $(LDLIBS)

resource.res: resource.rc
	$(WINDRES) resource.rc -O coff -o $@

include common.mk
